# get trade orders by specified filter

### Get trade orders by list of order numbers 
POST {{apiUrl}} HTTP/1.1
SOAPAction: http://tempuri.org/GetTradeOrders
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <GetTradeOrders xmlns="http://tempuri.org/">
         <req>
            <Credentials>
               <UserName>{{userName}}</UserName>
               <Password>{{password}}</Password>
            </Credentials>
            <identify>{{identify}}</identify>
            <Args>
                <OrderNos>
                    <string>10001</string>
                    <string>10002</string>
                </OrderNos>
            </Args>
            <Fields>
                {{allOrderFields}}
            </Fields>
         </req>
      </GetTradeOrders>
   </soap:Body>
</soap:Envelope>

### Get trade orders by states
POST {{apiUrl}} HTTP/1.1
SOAPAction: http://tempuri.org/GetTradeOrders
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <GetTradeOrders xmlns="http://tempuri.org/">
         <req>
            <Credentials>
               <UserName>{{userName}}</UserName>
               <Password>{{password}}</Password>
            </Credentials>
            <identify>{{identify}}</identify>
            <Args>
                <States>
                    <string>Filled</string>
                    <string>Settled</string>
                </States>
            </Args>
            <Fields>
                {{allOrderFields}}
            </Fields>
         </req>
      </GetTradeOrders>
   </soap:Body>
</soap:Envelope>

### Get trade orders by created date range
POST {{apiUrl}} HTTP/1.1
SOAPAction: http://tempuri.org/GetTradeOrders
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
   <soap:Body>
      <GetTradeOrders xmlns="http://tempuri.org/">
         <req>
            <Credentials>
               <UserName>{{userName}}</UserName>
               <Password>{{password}}</Password>
            </Credentials>
            <identify>{{identify}}</identify>
            <Args>
                <CreatedDateFrom>{{$datetime iso8601 -3 d}}</CreatedDateFrom>
                <CreatedDateTo>{{$datetime iso8601}}</CreatedDateTo>
            </Args>
            <Fields>
                {{allOrderFields}}
            </Fields>
         </req>
      </GetTradeOrders>
   </soap:Body>
</soap:Envelope>
