### create a new open holding account owned by specific person
@ownerId = b282a98b-5941-4a8b-922d-335ac1fbb7ed
@baseCurrencyCode = SEK

POST {{apiUrl}} HTTP/1.1
SOAPAction: "http://tempuri.org/CreateAccounts"
Content-Type: text/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <CreateAccounts xmlns="http://tempuri.org/">
      <req>
        <Credentials>
            <UserName>{{userName}}</UserName>
            <Password>{{password}}</Password>
        </Credentials>
        <identify>{{identify}}</identify>
        <Entities>
          <Account>
            <Owner>{{ownerId}}</Owner>
            <AccountTypeKey>HoldingAccount</AccountTypeKey>
            <BaseCurrencyCode>{{baseCurrencyCode}}</BaseCurrencyCode>
            <AccountStatus>1</AccountStatus>
          </Account>
        </Entities>
      </req>
    </CreateAccounts>
  </soap:Body>
</soap:Envelope>
