### get business transactions affecting a specified account
@accountId = 48d42589-8b74-4804-b762-c7f609b8a3cd

POST {{apiUrl}} HTTP/1.1
SOAPAction: "http://tempuri.org/GetBusinessTransactions"
Content-Type: text/xml; charset=utf-8

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <GetBusinessTransactions xmlns="http://tempuri.org/">
            <req>
                <Credentials>
                    <UserName>{{userName}}</UserName>
                    <Password>{{password}}</Password>
                </Credentials>
                <identify>{{identify}}</identify>
                <Args>
                    <Accounts>
                        <guid>{{accountId}}</guid>
                    </Accounts>
                </Args>
                <Fields>
                    {{allBusinessTransactionFields}}
                </Fields>
            </req>
        </GetBusinessTransactions>
    </s:Body>
</s:Envelope>


### get business transactions by range of trade dates (last 3 days)
POST {{apiUrl}} HTTP/1.1
SOAPAction: "http://tempuri.org/GetBusinessTransactions"
Content-Type: text/xml; charset=utf-8

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
        <GetBusinessTransactions xmlns="http://tempuri.org/">
            <req>
                <Credentials>
                    <UserName>{{userName}}</UserName>
                    <Password>{{password}}</Password>
                </Credentials>
                <identify>{{identify}}</identify>
                <Args>
                    <TradeDateFrom>{{$datetime iso8601 -3 d}}</TradeDateFrom>
                    <TradeDateTo>{{$datetime iso8601}}</TradeDateTo>
                </Args>
                <Fields>
                    {{allBusinessTransactionFields}}
                </Fields>
            </req>
        </GetBusinessTransactions>
    </s:Body>
</s:Envelope>